TARGET := iphone:clang:latest:latest
INSTALL_TARGET_PROCESSES = Yubo

TWEAK_NAME = FuckYuboChat

FuckYuboChat_FILES = Tweak.m
FuckYuboChat_CFLAGS = -fobjc-arc

include $(THEOS)/makefiles/common.mk
include $(THEOS_MAKE_PATH)/tweak.mk
