BUNDLE_NAME = BSCImagePrefs

BSCImagePrefs_FILES = BSCIRootVC.m
BSCImagePrefs_CFLAGS = -fobjc-arc
BSCImagePrefs_FRAMEWORKS = UIKit
BSCImagePrefs_PRIVATE_FRAMEWORKS = Preferences
BSCImagePrefs_INSTALL_PATH = /Library/PreferenceBundles

include $(THEOS)/makefiles/common.mk
include $(THEOS_MAKE_PATH)/bundle.mk