BUNDLE_NAME = ArizonaPrefs

ArizonaPrefs_FILES = ArizonaVC.m
ArizonaPrefs_CFLAGS = -fobjc-arc
ArizonaPrefs_LIBRARIES = gcuniversal
ArizonaPrefs_FRAMEWORKS = UIKit
ArizonaPrefs_PRIVATE_FRAMEWORKS = Preferences OnBoardingKit
ArizonaPrefs_INSTALL_PATH = /Library/PreferenceBundles

include $(THEOS)/makefiles/common.mk
include $(THEOS_MAKE_PATH)/bundle.mk
