TARGET := iphone:clang:latest:latest
INSTALL_TARGET_PROCESSES = Instagram

TWEAK_NAME = IGConfirm

IGConfirm_FILES = IGConfirm.m
IGConfirm_CFLAGS = -fobjc-arc

include $(THEOS)/makefiles/common.mk
include $(THEOS_MAKE_PATH)/tweak.mk
