TARGET := iphone:clang:latest:14.0
INSTALL_TARGET_PROCESSES = Preferences

TWEAK_NAME = Zaire

Zaire_FILES = Zaire.mm
Zaire_CFLAGS = -fobjc-arc

include $(THEOS)/makefiles/common.mk
include $(THEOS_MAKE_PATH)/tweak.mk
