BUNDLE_NAME = StealthCCPrefs

StealthCCPrefs_FILES = STLRootVC.m
StealthCCPrefs_CFLAGS = -fobjc-arc
StealthCCPrefs_FRAMEWORKS = UIKit
StealthCCPrefs_PRIVATE_FRAMEWORKS = Preferences
StealthCCPrefs_INSTALL_PATH = /Library/PreferenceBundles

include $(THEOS)/makefiles/common.mk
include $(THEOS_MAKE_PATH)/bundle.mk