BUNDLE_NAME = ArresPrefs

ArresPrefs_FILES = ArresVC.m
ArresPrefs_CFLAGS = -fobjc-arc
ArresPrefs_FRAMEWORKS = UIKit
ArresPrefs_PRIVATE_FRAMEWORKS = Preferences
ArresPrefs_INSTALL_PATH = /Library/PreferenceBundles

include $(THEOS)/makefiles/common.mk
include $(THEOS_MAKE_PATH)/bundle.mk
