TARGET := iphone:clang:latest:latest
INSTALL_TARGET_PROCESSES = Zoho\ Mail

TWEAK_NAME = ZohoPopToRoot

ZohoPopToRoot_FILES = Tweak.m
ZohoPopToRoot_CFLAGS = -fobjc-arc

include $(THEOS)/makefiles/common.mk
include $(THEOS_MAKE_PATH)/tweak.mk
