BUNDLE_NAME = RenPrefs

RenPrefs_FILES = RenRootVC.m
RenPrefs_CFLAGS = -fobjc-arc
RenPrefs_FRAMEWORKS = UIKit
RenPrefs_PRIVATE_FRAMEWORKS = Preferences
RenPrefs_INSTALL_PATH = /Library/PreferenceBundles

include $(THEOS)/makefiles/common.mk
include $(THEOS_MAKE_PATH)/bundle.mk
