TARGET := iphone:clang:latest:latest
INSTALL_TARGET_PROCESSES = Argo

TWEAK_NAME = ByeByeAdvisoryLabel

ByeByeAdvisoryLabel_FILES = Tweak.m
ByeByeAdvisoryLabel_CFLAGS = -fobjc-arc

include $(THEOS)/makefiles/common.mk
include $(THEOS_MAKE_PATH)/tweak.mk
