BUNDLE_NAME = NetflixToggle

NetflixToggle_FILES = NetflixToggle.m
NetflixToggle_CFLAGS = -fobjc-arc
NetflixToggle_INSTALL_PATH = /Library/ControlCenter/Bundles/
NetflixToggle_BUNDLE_EXTENSION = bundle
NetflixToggle_PRIVATE_FRAMEWORKS = ControlCenterUIKit

include $(THEOS)/makefiles/common.mk
include $(THEOS_MAKE_PATH)/bundle.mk
