BUNDLE_NAME = AutoRespringPrefs

AutoRespringPrefs_FILES = AutoRespringVC.m
AutoRespringPrefs_CFLAGS = -fobjc-arc
AutoRespringPrefs_FRAMEWORKS = UIKit
AutoRespringPrefs_PRIVATE_FRAMEWORKS = Preferences
AutoRespringPrefs_INSTALL_PATH = /Library/PreferenceBundles

include $(THEOS)/makefiles/common.mk
include $(THEOS_MAKE_PATH)/bundle.mk
