BUNDLE_NAME = KaiaToggle

KaiaToggle_FILES = KaiaToggle.m
KaiaToggle_CFLAGS = -fobjc-arc
KaiaToggle_FRAMEWORKS = UIKit
KaiaToggle_PRIVATE_FRAMEWORKS = ControlCenterUIKit
KaiaToggle_INSTALL_PATH = /Library/ControlCenter/Bundles/
KaiaToggle_BUNDLE_EXTENSION = bundle

include $(THEOS)/makefiles/common.mk
include $(THEOS_MAKE_PATH)/bundle.mk
