BUNDLE_NAME = SelenePrefs

SelenePrefs_FILES = SeleneVC.m
SelenePrefs_CFLAGS = -fobjc-arc
SelenePrefs_FRAMEWORKS = UIKit
SelenePrefs_PRIVATE_FRAMEWORKS = Preferences
SelenePrefs_INSTALL_PATH = /Library/PreferenceBundles

include $(THEOS)/makefiles/common.mk
include $(THEOS_MAKE_PATH)/bundle.mk
