TARGET := iphone:clang:latest:14.0
INSTALL_TARGET_PROCESSES = SpringBoard

TWEAK_NAME = Wisteria

Wisteria_FILES = Tweak.mm
Wisteria_CFLAGS = -fobjc-arc
Wisteria_FRAMEWORKS = BulletinBoard

include $(THEOS)/makefiles/common.mk
include $(THEOS_MAKE_PATH)/tweak.mk
